language: ruby
cache: bundler

rvm:
  - 2.2.0
  - 2.1.5
  - 2.0.0
  - 1.9.3

install: bundle install --jobs=3 --retry=3 && gem install sqlite3  

script: 'cd test/dummy && bundle exec rake db:setup && cd ../.. && bundle exec rake coverage=true'

addons:
  code_climate:
    repo_token: 2726f8ee8090c38b972be023cec4999e1057c02d1ad27f9699d01dc7e2385221
