language: ruby
cache: bundler

rvm:
  - 2.3.3
  - 2.2.6
  - 2.1.10
  - 2.0.0

install: bundle install --jobs=3 --retry=3 && gem install sqlite3

script: 'cd test/dummy && bundle exec rake db:setup && cd ../.. && bundle exec rake COVERAGE=true'

addons:
  code_climate:
    repo_token: 2726f8ee8090c38b972be023cec4999e1057c02d1ad27f9699d01dc7e2385221
